# Evaluate the Custom Bagging Classifier

In [37]:
# Import the ncessary libraries and modules
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
from bagging import CustomBaggingClassifier
from sklearn.ensemble import BaggingClassifier

### Evaluate the Custom Bagging Classifier on the Scikit-Learn **Iris dataset** and compare the results with the Scikit-learn `BaggingClassifier`. Print the **accuracy score** and the **confusion matrix** for both models. For replicability, use a `random_state` of 43 for the `train_test_split` and a `test_size` of 0.25. Use a `DecisionTreeClassifier` of `max_depth=2` as the base estimator and a `n_estimators=10` for both models.

In [40]:
iris = datasets.load_iris()
X, y = iris.data, iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=43)
tree = DecisionTreeClassifier(criterion='entropy', random_state=43, max_depth=2)

bag = BaggingClassifier(base_estimator=tree, oob_score=True, bootstrap=True, n_estimators=10, random_state=43)
bag.fit(X_train, y_train)
bag_pred = bag.predict(X_test)
bag_cm = confusion_matrix(y_test, bag.predict(X_test))

num_correct_predictions = (bag_pred == y_test).sum()
accuracy = (num_correct_predictions / y_test.shape[0]) * 100

print("sklearn bagging classifier:")
print("accuracy: \n", accuracy)
print("confusion matrix: \n", bag_cm)

custom = CustomBaggingClassifier(base_estimator=DecisionTreeClassifier(max_depth=2), n_estimators=10, random_state=43)
custom.fit(X_train, y_train)
custom_pred = custom.predict(X_test)
custom_cm = confusion_matrix(y_test, custom.predict(X_test))

num_correct_predictions = (custom_pred == y_test).sum()
accuracy = (num_correct_predictions / y_test.shape[0]) * 100

print("\ncustom bagging classifier")
print("accuracy: \n", accuracy)
print("confusion matrix: \n", custom_cm)

sklearn bagging classifier:
accuracy: 
 94.73684210526315
confusion matrix: 
 [[14  0  0]
 [ 0 12  0]
 [ 0  2 10]]

custom bagging classifier
accuracy: 
 97.36842105263158
confusion matrix: 
 [[14  0  0]
 [ 0 12  0]
 [ 0  1 11]]


C:\Users\Emma\miniconda3\envs\cs4347\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\Emma\miniconda3\envs\cs4347\lib\site-packages\sklearn\ensemble\_bagging.py:791: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
C:\Users\Emma\miniconda3\envs\cs4347\lib\site-packages\sklearn\ensemble\_bagging.py:797: RuntimeWarning: invalid value encountered in divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
